version: "3.8"
services:
  database:
    immage: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - clarusnet

  my-app:
    image: ramazancw/bookstore:latest
    restart: always
    depends-on:
      - database
    port:
      - "80" : "80"
    
networks:
  clarusnet:
    driver: bridge

    

    